application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: helloworld.php

- url: /display
  static_dir: display

- url: /insert
  static_dir: insert

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

