application: inventorymchocolat
version: 1
runtime: php
api_version: 1

handlers:

- url: /.
  script: helloworld.php

- url: /displayAssortments
  script: displayAssortments.php

- url: /insertAssortments
  script: insertAssortments.php

- url: /stylesheets
  static_dir: stylesheets

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img