application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: helloworld.php

- url: /displayAssortments
  script: displayAssortments.php

- url: /(.*)?/(.*)\.php$
  static_dir: \1/\2.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

