application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: helloworld.php

- url: /displayAssortments
  script: displayAssortments.php

- url: /insertAssortments
  script: insertAssortments.php

- url: /css*
  static: css/

- url: /js*
  static: js/

- url: /img*
  static: img/

