application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: index.php
  
- url: /index.php
  script: index.php

- url: /(.*)?/(.*)\.php$
  script: \1/\2.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img
  
- url: /functions.php
  script: functions.php
  
- url: /display
  static_dir: display

