application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: index.php
  login: required

- url: /(.*)?/(.*)\.php$
  script: \1/\2.php
  login: required

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /header.php
  script: header.php

- url: /functions.php
  script: functions.php