application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: helloworld.php

- url: /(.*)?/(.*)\.php$
  script: \1/\2.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /rawMaterials.html
  static_files: rawMaterials.html
  upload: rawMaterials.html
  
- url: /functions.php
  script: functions.php

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
