application: inventorymchocolat
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /
  script: helloworld.php

- url: /displayAssortments
  script: displayAssortments.php

- url: /insertAssortments
  script: insertAssortments.php

- url: /insertBatch
script: insertBatch.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

