application: inventorymchocolat
version: 1
runtime: php
api_version: 1

handlers:

- url: /
  script: helloworld.php

- url: /displayAssortments
  script: displayAssortments.php

- url: /insertAssortments
  script: insertAssortments.php

